// Copyright (c) 2015 TeamSnap. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "TSDKCollectionObject.h"
#import "TSDKObjectsRequest.h"
#import "TSDKProcessBulkObjectProtocol.h"

@interface TSDKMember : TSDKCollectionObject <TSDKProcessBulkObjectProtocol>

@property (nonatomic, weak) NSString *lastName; //Example: Manager
@property (nonatomic, weak) NSDate *createdAt; //Example: 2016-01-27T22:21:19Z
@property (nonatomic, assign) NSInteger teamId; //Example: 1
@property (nonatomic, weak) NSString *hideAddress; //Example: **NULL**
@property (nonatomic, assign) BOOL isOwnershipPending; //Example: <null>
@property (nonatomic, weak) NSString *addressStreet2; //Example: **NULL**
@property (nonatomic, assign) BOOL isPushable; //Example: 0
@property (nonatomic, weak) NSString *addressState; //Example: **NULL**
@property (nonatomic, assign) BOOL hasFacebookPostScoresEnabled; //Example: 0
@property (nonatomic, weak) NSString *hideAge; //Example: **NULL**
@property (nonatomic, weak) NSString *invitationDeclined; //Example: **NULL**
@property (nonatomic, assign) BOOL isInvitable; //Example: 0
@property (nonatomic, weak) NSString *addressZip; //Example: **NULL**
@property (nonatomic, weak) NSDate *lastLoggedInAt; //Example: 2016-02-02T04:06:25Z
@property (nonatomic, weak) NSString *invitationCode; //Example: **NULL**
@property (nonatomic, weak) NSString *position; //Example: **NULL**
@property (nonatomic, weak) NSDate *birthday; //Example:
@property (nonatomic, assign) BOOL isEmailable; //Example: 1
@property (nonatomic, assign) BOOL isInvited; //Example: 0
@property (nonatomic, assign) BOOL isActivated; //Example: 1
@property (nonatomic, weak) NSString *addressStreet1; //Example: **NULL**
@property (nonatomic, assign) BOOL isNonPlayer; //Example: 0
@property (nonatomic, weak) NSString *addressCity; //Example: **NULL**
@property (nonatomic, assign) BOOL isAgeHidden; //Example: <null>
@property (nonatomic, weak) NSString *firstName; //Example: Manny
@property (nonatomic, assign) BOOL isManager; //Example: 1
@property (nonatomic, weak) NSString *jerseyNumber; //Example: **NULL**
@property (nonatomic, assign) NSInteger userId; //Example: 7
@property (nonatomic, weak) NSString *gender; //Example: **NULL**
@property (nonatomic, assign) BOOL isOwner; //Example: 0
@property (nonatomic, assign) BOOL isAddressHidden; //Example: <null>
@property (nonatomic, weak) NSDate *updatedAt; //Example: 2016-02-02T04:06:25Z
@property (nonatomic, assign) BOOL isAlertable; //Example: 0
@property (nonatomic, weak) NSURL *linkBroadcastEmails;
@property (nonatomic, weak) NSURL *linkBroadcastEmailAttachments;
@property (nonatomic, weak) NSURL *linkMemberLinks;
@property (nonatomic, weak) NSURL *linkMemberPreferences;
@property (nonatomic, weak) NSURL *linkTeam;
@property (nonatomic, weak) NSURL *linkMemberPhoneNumbers;
@property (nonatomic, weak) NSURL *linkStatisticData;
@property (nonatomic, weak) NSURL *linkMemberEmailAddresses;
@property (nonatomic, weak) NSURL *linkForumSubscriptions;
@property (nonatomic, weak) NSURL *linkSentMessages;
@property (nonatomic, weak) NSURL *linkLeagueCustomData;
@property (nonatomic, weak) NSURL *linkContactPhoneNumbers;
@property (nonatomic, weak) NSURL *linkContactEmailAddresses;
@property (nonatomic, weak) NSURL *linkTeamMedia;
@property (nonatomic, weak) NSURL *linkReceivedMessages;
@property (nonatomic, weak) NSURL *linkTrackedItemStatuses;
@property (nonatomic, weak) NSURL *linkForumTopics;
@property (nonatomic, weak) NSURL *linkTeamMediumComments;
@property (nonatomic, weak) NSURL *linkCustomFields;
@property (nonatomic, weak) NSURL *linkAssignments;
@property (nonatomic, weak) NSURL *linkCustomData;
@property (nonatomic, weak) NSURL *linkMemberStatistics;
@property (nonatomic, weak) NSURL *linkAvailabilities;
@property (nonatomic, weak) NSURL *linkMemberBalances;
@property (nonatomic, weak) NSURL *linkUser;
@property (nonatomic, weak) NSURL *linkForumPosts;
@property (nonatomic, weak) NSURL *linkBroadcastAlerts;
@property (nonatomic, weak) NSURL *linkMemberPayments;
@property (nonatomic, weak) NSURL *linkLeagueCustomFields;
@property (nonatomic, weak) NSURL *linkLeagueRegistrantDocuments;
@property (nonatomic, weak) NSURL *linkContacts;
@property (nonatomic, weak) NSURL *linkMemberFiles;
@property (nonatomic, weak) NSURL *linkMemberPhoto;
@property (nonatomic, weak) NSURL *linkMemberThumbnail;

// Not AutoGenerated:
#if TARGET_OS_IPHONE
-(void)getMemberPhotoWithCompletion:(TSDKImageCompletionBlock)completion;
-(void)getMemberThumbnailWithCompletion:(TSDKImageCompletionBlock)completion;
#endif

@property (readonly) NSString *fullName;
@property (assign, nonatomic) TSDKTeam *team;
@property (strong, nonatomic) NSMutableDictionary *contacts;
@property (strong, nonatomic) NSMutableDictionary *emailAddresses;
@property (strong, nonatomic) NSMutableDictionary *phoneNumbers;


- (BOOL)isAtLeastManager;
- (BOOL)isAtLeastOwner;

- (NSInteger)age;

@end

@interface TSDKMember (ForwardedMethods)

-(void)getBroadcastEmailsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getBroadcastEmailAttachmentsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberLinksWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberPreferencesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getTeamWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberPhoneNumbersWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getStatisticDataWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberEmailAddressesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getForumSubscriptionsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getSentMessagesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getLeagueCustomDataWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getContactPhoneNumbersWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getContactEmailAddressesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getTeamMediaWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getReceivedMessagesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getTrackedItemStatusesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getForumTopicsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getTeamMediumCommentsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getCustomFieldsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getAssignmentsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getCustomDataWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberStatisticsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getAvailabilitiesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberBalancesWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getUserWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getForumPostsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getBroadcastAlertsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberPaymentsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getLeagueCustomFieldsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getLeagueRegistrantDocumentsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getContactsWithCompletion:(TSDKArrayCompletionBlock)completion;
-(void)getMemberFilesWithCompletion:(TSDKArrayCompletionBlock)completion;

@end